### ISSUE TITLE
Bombard youtube with less search queries (Spotify main offender)

### ISSUE THREAD

**Issue by napstr** [Frederikam/FredBoat#259]
Since we turned off cookies due to a lot of 503s happening on Youtube's side, Youtube started flagging us as a suspicious and presenting a captcha for searches occasionally.
One of the main offenders is the Spotify playlist loader, which searches for each song's name and artist from a Spotify playlist, resulting in hundreds of search queries at the same time.

We could try rate limiting the searches, which would lead to an initially longer loading time for such a playlist, while at the same time caching the search results. The latter can be a thing for all searches, not just the ones done when loading a Spotify playlist, and should speed up things overall at the cost of some (?) memory.

To discuss: What would be a good caching duration? What's an acceptable memory cost?

#### Steps to resolve
updated 28th august

- [x] ~~Rate limit searches when loading a Spotify playlist~~ This did not help much, Youtube still flags us at a rate of 1 search per second, which is ridiculously slow already. Instead: Have a single thread load the Spotify playlists.
- [x] Cache all searches on a search provider scope (only successful ones!) #261
- [x] Patron only: Use Youtube API if the lavaplayer search returns a 503 #261
- [x] Fallback to Soundcloud search if none of the above provided a result #261

**Comment by Frederikam** [comment]
Why memory? Why not persist it to the DB?

**Comment by napstr** [comment]
Sure, that's a great option. I wanted to try Guava's Cache for this. I wonder if it supports caching into a database out of the box.

**Comment by Frederikam** [comment]
There's always EHCache as the second level cache

**Comment by napstr** [comment]
Nope, Guava isn't meant for the db, just memory.
![image](https://user-images.githubusercontent.com/6048348/29750331-2299aa5a-8b3e-11e7-9232-9f0d41287d51.png)

https://github.com/google/guava/wiki/CachesExplained#applicability

**Comment by Frederikam** [comment]
But we *do* have EGCache already hooked up to Hibernate for entity caching

**Comment by napstr** [comment]
I don't think it's a big issue, the main difference to using Guava will be handling the expiration.

**Comment by Frederikam** [comment]
We could also use ehcache to persist directly to the FS without the DB, with an expiration

**Comment by napstr** [comment]
Ratelimiting the searches is a bit tricky. When I loaded a 1488 track playlist with the current, unlimited code, it got 900 something results back before being flagged by Youtube.
Then I put a rate limit in place that fires a search request only once per second, and ended up getting flagged after 100 something results.

**Comment by napstr** [comment]
So far, I failed to find a watertight way to avoid being flagged by Youtube. I also don't think there is a good way to come back from a flagged status (= resolving a recaptcha. recaptchas are consider so hard that not even jdownloader solves them, they just proxy them to your browser for you to solve).

So the main goal is still just to reduce general search load. So here's the proposed flow of a regular search:

Cache Youtube -> Search with lavaplayer -> Search with Youtube API (Patron only) -> Cache Soundcloud -> Search with Soundcloud

Going to the next step only if the previous one was unsuccessful.
Lemme know how you like that.

**Comment by Frederikam** [comment]
Maybe use the official YouTube API as a backup? We have limited usage, but should be plenty to supplement with.

**Comment by Kurozume** [comment]
Regarding ratelimiting the searches;
 - Would it be possible to queue x songs at a time?
Aka: 
 > Song 1 starts and Song 2 is searched and queued
 > Song 2 starts and Song 3 is searched and queued
etc.
etc.
or would the nature of the way songs are queued prevent a system like this?

**Comment by majorcyto** [comment]
How come the Youtube API isn't already used by the way? Or used in conjunction with current search, Which I know is what Frederikam is already suggesting. But I am still just curious as to why API Search was never used. Is it inferior in some way?

You can get API raises from Google if you hit your limit as long as your project is legit.

**Comment by Shredder121** [comment]
This isn't some academic project, it's not research.
It's literally pulling videos from YouTube, so don't know how legit that is.

The main reason it wasn't used is the inferior volume, as far as I can tell.



> Would it be possible to queue x songs at a time?

Maybe yeah, then we'd have to rework it so the search context it held onto for a bit longer.

**Comment by Frederikam** [comment]
Yeah FredBoat is against the ToS. They don't allow scrapers or bots downloading their videos.

**Comment by majorcyto** [comment]
Ah ok, woops haha. Thank you for the explanation. 👍

**Comment by napstr** [comment]
#261 Implements all of these.
