### ISSUE TITLE
Some Cleanup

### ISSUE THREAD

**Issue by napstr** [Frederikam/FredBoat#317]
- [x] Sprinkle in ~~more~~ all of them JSR 305 annotations (`@Nonnull` and `@Nullable`) for parameters and return values, including adding their requirement to CONTRIBUTING.md
- [x] Remove legacy scope system and oauth stuff (?) #320
- [x] add I18n convenience methods on the Context that also make sure the resource bundle is loaded exactly once. #337
- [x] add CI build number to the version / general awareness of FredBoat #319 

are things I'm having on my short list of small annoying things that just need to be done so I'll do them in the near future.
Please let me know of any objections/additions to that list @Frederikam

**Comment by Frederikam** [comment]
> Remove legacy scope system and oauth stuff (?)

Please do. Also I've been wanting to get rid of all deprecated method calls, we have quite a few.

**Comment by napstr** [comment]
More "deprecated" things
- [ ] remove LeetCommand
- [ ] migrate away from Unirest
- [ ] remove TalkCommand/JCA (cleverbot.io) (@Frederikam or should we try again salvaging this)

**Comment by Nanabell** [comment]
imo we should drop cleverbot completly

**Comment by napstr** [comment]
- [ ] document our procedure to add I18n strings in CONTRIBUTING.MD

**Comment by napstr** [comment]
- [ ] update credentials.yaml.example both in the repo and on the website; add sentence about not using tab characters to selfhosting docs

**Comment by napstr** [comment]
- [ ] #312 needs a follow up

**Comment by napstr** [comment]
I think adding those Nullable/Nonnull JSR annotations to the _whole_ current code base is too big of a task to execute. In some places they are overkill, too.
I'd rather have us regular contributors @Frederikam @Shredder121 @Nanabell agree to add them to new code, especially in places where actually Nullable values are used, and gradually add them to existing code when we discover them missing + add a note to the CONTRIBUTING.MD. Sounds good?

**Comment by Shredder121** [comment]
Yeah sounds good to me.
