### ISSUE TITLE
Rework user/guild counts

### ISSUE THREAD

**Issue by napstr** [Frederikam/FredBoat#351]
todo:

- [x] use JDAs recently introduced CacheView to count entities where applicable instead of our homebrewed "hacks" (@Shredder121 rip) #352
- [x] instead of counting unique users (and other global stats) on demand, have an agent count them each minute (?) and then serve those numbers for requests. This should even out workload, make /stats served by the API fast, and reduce possible abuse. #352
- [x] count more JDA entity things like channels etc #352
- [x] add these stats to the metrics PR 79e43915334b48aeed3f32993a54d1972c05857a

**Comment by Shredder121** [comment]
What about increasing the interval to 5 minutes, otherwise it will be like running `;;stats` every minute.
And IMO slightly stale info, 2,5 minutes on average, is okay.
with 1 minute that's 30 seconds on average

**Comment by napstr** [comment]
5 minutes sounds like a good enough :tm: resolution
