### ISSUE TITLE
Integration testing of FredBoat and Lavalink

### ISSUE THREAD

**Issue by Frederikam** [Frederikam/FredBoat#384]
I'm working on setting up [an integration test environment](https://ci.fredboat.com/viewType.html?buildTypeId=FredBoat_Integration). This build config will be triggered by a webhook when either FredBoat or Lavalink is updated.

I'm looking for people who are interested in contributing tests once this is working.

## Why is writing integration tests important?
https://www.reddit.com/r/ProgrammerHumor/comments/61qnnk/2_unit_tests_0_integration_tests/

## Todo
- [ ] Actually get the environment running
- [ ] Test lavalink join/leave
- [ ] Test lavalink destroy
- [ ] Playing music
- [ ] Anything you could think of in terms of commands (like ;;play returning search results)
- [ ] Tests interfacing with the database (like permissions and configuration)

**Comment by Frederikam** [comment]
This issue is now a year old :tada: 

In the meanwhile, this has been pretty much solved with sentinel.
